config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root to: "home#index"
	devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "users/registrations" }

	resources :after_register
  resources :locations
  resources :children do
    resources :donations
  end
  resources :contributors

  get 'donor/profile', to: 'profiles#donor_profile', as: 'donor_profile'
  get 'student/profile', to: 'profiles#student_profile', as: 'student_profile'
  get 'parent/profile', to: 'profiles#parent_profile', as: 'parent_profile'
  get 'public/profile', to: 'profiles#public_profile', as: 'public_profile'
  get 'child/search', to: 'children#child_search', as: 'child_search'
  get 'key_students', to: 'contributors#key_student', as: 'key_student'
	get 'user_page/show', to: 'user_page#show', as: 'user_page_show'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

	def donor_profile
		@helped_students = []
		@donor = current_user if current_user.has_role? :donor
		@donations = Donation.donated_to_students(current_user)
		@donations.each do |donation|
			@helped_students << donation.child  
		end
	end

	def parent_profile
		@parent = current_user if current_user.has_role? :parent
	end

	def student_profile
		@student = Child.find_by(child_id: current_user.id) if current_user.has_role? :student
		@student_donors = []
	    @donations = Donation.donating_to_student(@student)
	    @donations.each do |donation|
	      @student_donors << donation.user  
	    end
	end

	def public_profile
		@user = User.find(params[:profile])
	end

end

app/helpers/profiles_helper.rb
module ProfilesHelper

	def percentage
		
		
	end
end

app/views/profiles/donor_profile.html.erb
<br>
<div id="donnor-page">
	<div class="row">
		<div id="user-info" class="small-12">
			<div class="small-12">
				<%= image_tag @donor.avatar.url(:thumb), class: "circle-img float-center" %>
		    </div>
		    <br>
		    <div class="text-center">
		    	<h6><%= @donor.first_name %> <%= @donor.last_name %></h6>
		    	<h6><%= @donor.day_of_birth %></h6>
		    	<h6><%= @donor.email %></h6>
		    </div>
		</div>
	</div>
    <br>
    <% if @helped_students.count == 0 %>
    	<div class="row">
    		<div class="small-12 text-center">
    			<h4>You haven't helped anyone yet</h4>
    			<%= link_to "Help someone!", child_search_path, class: "button"%>
    		</div>
    		
    	</div>
    <% else %>
	    <div id="user-card" class="row">
		    <div class="small-10 float-center">
		    	<h4>You have helped</h4>
		    	<% @helped_students.uniq.each do |student| %>
		    	<div  class="card text-center small-8 small-push-2 medium-4 medium-pull-0 end column">
				    <div class="circle-img">
				    	<%= link_to child_path(student) do %>
				    		<%= image_tag student.photo.url(:thumb), class: "circle-img" %>
				    	<% end %>
				    </div>
			        <div>
						<h6><%= student.first_name%></h6>
						<h6 class="truncate"><%= student.email_address %></h6>
						<h6><%= student.birthday %></h6>
				    </div>
			    </div>
			    <% end %>
		    </div>
	    </div>
    <% end %>
    <br>
</div>
<br>

app/views/profiles/parent_profile.html.erb
<br>
<div id="parent-page">
	<div class="row">
		<div id="user-info" class="callout small-10 small-push-1 medium-6 medium-push-3 large-4 large-push-4 columns">
			<div class="small-12 columns">
				<%= image_tag @parent.avatar.url(:thumb), class: "circle-img float-center" %>
		    </div>
		    <div class="small-12 text-center columns">
		    	<br>
		    	<h6 class="truncate"><%= @parent.first_name %> <%= @parent.last_name %></h6>
		    	<h6 class="truncate"><%= @parent.email %></h6>
		    	<h6><%= @parent.day_of_birth %></h6>
		    	<h6 class="truncate"><%= @parent.biography %></h6>
		    </div>
		</div>
	</div>
    <div id="user-card" class="row">
	    <div class="small-12 columns">
	    	<h4>My Children</h4>
	    	<% if @parent.children.count == 0 %>
	    		<div class="callout medium-6 medium-pull-3 text-center columns">
	    			<h4><i>Add your children to stablish funding goal!</i></h4>
	    		</div>
	    	<% else %>
		    	<% @parent.children.each do |child| %>
				    <div  class="card text-center small-8 small-push-2 medium-4 medium-pull-0 end columns">
				      <div class="circle-img">
				        <%= link_to image_tag(child.photo.url(:thumb), class:'circle-img'), child_path(child) %>
				      </div>
				      <div>
				          <h6 class="truncate"><%= child.first_name %> <%= child.last_name %></h6>
				          <h6 class="truncate"><%=  child.user_name %></h6>
				          <h6><%=  child.birthday %></h6>
				          <h6 class="truncate"><%=  child.email_address %></h6>
				      </div>
				    </div>
				<% end %>
			<% end %>
	    </div>
    </div>
    <div class="row">
    	<div class="small-12 text-center columns">
    		<br>
    		<%= link_to "Add Child", new_child_path, class: "button" %>
    	</div>
    </div>
    <br>
    <div id="user-card" class="row">
	    <div class="small-12 columns">
	    	<h4>My Contributors</h4>
	    	<% if @parent.contributors.count == 0 %>
	    		<div class="callout medium-6 medium-pull-3 text-center columns">
	    			<h4><i>Invite contributors to reach your children goals faster!</i></h4>
	    		</div>
	    	<% else %>
		    	<% @parent.contributors.each do |contributor| %>
				    <div class="card text-center small-8 small-push-2 medium-4 medium-push-0 end columns">
				      <div class="circle-img">
				        <%= link_to image_tag("slide01.jpg", class:'circle-img'), contributor_path(contributor) %>
				      </div>
				      <div>
				        <h6 class="truncate"><%=  contributor.first_name %> <%=  contributor.last_name %></h6>
				        <h6 class="truncate"><%=  contributor.email_address %></h6>
				        <h6 style="margin-bottom: 40px;"><%= relationship(contributor.relationship) %></h6>
				      </div>
				    </div>
				<% end %>
			<% end %>
	    </div>
    </div>
    <br>
    <div class="row">
    	<div class="small-12 text-center">
    		<%= link_to "Invite Contributor", new_contributor_path, class: "button" %>
    	</div>
    </div>
</div>
<br>

app/views/profiles/public_profile.html.erb
<br>
<div id="parent-page">
	<div class="row">
		<div id="user-info" class="small-12">
			<div class="small-12">
				<%= image_tag @user.avatar.url(:thumb), class: "circle-img float-center" %>
		    </div>
		    <br>
		    <div class="text-center">
		    	<h6><%= @user.first_name %> <%= @user.last_name %></h6>
		    	<h6><%= @user.email %></h6>
		    	<h6><%= @user.day_of_birth %></h6>
		    	<h6><%= @user.biography %></h6>
		    </div>
		</div>
	</div>   
<br>
</div>

app/views/profiles/student_profile.html.erb
<br>
<div id="student-page">
	<div class="row">
		<div id="user-info" class="small-12 medium-6 column">
			<div class="small-12">
				<%= image_tag @student.photo.url(:thumb), class: "circle-img float-center" %>
		    </div>
		    <br>
		    <div class="text-center">
		    	<h6><%= @student.first_name %> <%=  %></h6>
		    	<h6><%= @student.birthday %></h6>
		    	<h6 class="truncate"><%= @student.email_address %></h6>
		    </div>
	    </div>
	    <div class="small-12 medium-6 column">
	    	<div id="goal-container" class="">
	    		<div class="text-center">
	    			<h5><b>Student Fund Goal</b></h5>
	    		</div>
	    		<br>
	    		<div class="small-10 small-push-1">
	    			<h6><b>Goal:</b> <%= humanized_money_with_symbol @student.funding_goal %></h6>
	    			<h6><b>Current Amount:</b><%= @student.donations_amount_cents %></h6>
	    		</div>
			    <div class="progress small-10 small-push-1" role="progressbar" tabindex="0" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
  					<div class="progress-meter" style="width:<%= donationPercentage(@student.funding_goal_cents, @student.donations_amount_cents) %>;"><i class="fa fa-graduation-cap" aria-hidden="true"></i></div>
				</div>
				<div class="text-center">
				<% if can? :update, @child and @child.parent == current_user %>
					<%= link_to "Update Information", edit_child_path(@child), class: "button" %>
				<% end %>
				<%= link_to "Views Donations", child_donations_path(@student), class: "button" %>
			    </div>
		    </div>
	    </div>
	</div>
    <br>
    <% if @student.parent.present?%>
    	<div id="user-card" class="row">
	    	<div class="small-12 columns">
	    		<div class="small-12 medium-10 medium-push-1 columns">
		    		<h4>Student's Parents</h4>
		    	</div>
		    	<div  class="card text-center small-push-2 end column">
				    <div class="circle-img">
				        <%= image_tag("slide01.jpg",:class => "circle-img") %>
				    </div>
			        <div>
						<h6 class="truncate"><%= @student.parent.first_name %></h6>
						<h6><%= @student.parent.email_address %></h6>
				    </div>
			    </div>
		    </div>
	    </div>
	<% else %>
	<div class="row">
		<div class="callout small-12 medium-6 medium-push-3 text-center columns">
			<h4 style="color:black;"><i>You don't have a parent associated to your account</i></h4>
		</div>
	</div>
    <% end %>
    
    <br>
    <div id="user-card" class="row">
	    <div class="small-12">
	    	<div class="small-12 medium-10 medium-push-1">
	    		<h4>Student's donnors</h4>
	    	</div>
	    	<% @student_donors.uniq.each do |donor| %>
		    	<div  class="card text-center small-push-2 end column">
			      	<div class="circle-img">
			       		<%= image_tag("slide01.jpg",:class => "circle-img") %>
			      	</div>
			     	<div>
			        	<h6><%= donor.first_name %></h6>
			        	<h6 class="truncate"><%= donor.email %></h6>
			      	</div>
		    	</div>
		    <% end %>
	    </div>
    </div>
</div>
<br>