config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root to: "home#index"
	devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "users/registrations" }

	resources :after_register
  resources :locations
  resources :children do
    resources :donations
  end
  resources :contributors

  get 'donor/profile', to: 'profiles#donor_profile', as: 'donor_profile'
  get 'student/profile', to: 'profiles#student_profile', as: 'student_profile'
  get 'parent/profile', to: 'profiles#parent_profile', as: 'parent_profile'
  get 'public/profile', to: 'profiles#public_profile', as: 'public_profile'
  get 'child/search', to: 'children#child_search', as: 'child_search'
  get 'key_students', to: 'contributors#key_student', as: 'key_student'
	get 'user_page/show', to: 'user_page#show', as: 'user_page_show'
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
	before_action :set_child, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  
  def index
    @user = current_user
    @children = Child.my_sons(@user)
  end

  def child_search
    @children = Child.search(params)
  end

  def show
    #@amount = @child.donations.sum(:amount_cents)
    @amount = @child.donations_amount
    @amount_cents = @child.donations_amount_cents
    @student_donors = []
    @donations = Donation.donating_to_student(@child)
    @donations.each do |donation|
      @student_donors << donation.user  
    end
  end

  def new
    
  end

  def edit

  end

  def create
    @user = current_user
    @child = Child.new(child_params)
    @child.parent_id = @user.id
    @child.funding_goal.to_s.sub('$','')
    respond_to do |format|
      if @child.save
        format.html { redirect_to after_register_path(:your_children), notice: 'child was successfully created.' }
        format.json { render :show, status: :created, child: @child }
      else
        format.html { render :new }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @child.update(child_params)
        format.html { redirect_to @child, notice: 'child was successfully updated.' }
        format.json { render :show, status: :ok, child: @child }
      else
        format.html { render :edit }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @child.destroy
    respond_to do |format|
      format.html { redirect_to childs_url, notice: 'child was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_child
      @child = Child.find(params[:id])
    end

    def child_params
      params.require(:child).permit(:first_name, :last_name, :birthday, :user_name, :photo, :email_address, :parent_id, :funding_goal, :child_id)
    end
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/views/children/_form.html.erb
<%= form_for Child.new, builder: FoundationFormBuilder, remote: true, html: { multipart: true }, authenticity_token: true do |f| %>
  <div class="callout small small-12 medium-6 medium-push-3">
    <div class="field">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :birthdate %>
      <div class="small-10 small-push-1 medium-6 medium-push-3">
        <%= f.date_select :birthday, {order: [:day, :month, :year], prompt: { day: 'Day', month: 'Month', year: 'Year' }, start_year: Date.today.year - 18, end_year: Date.today.year - 100}, {required: true} %>
      </div>
    </div>
    <div class="field">
      <%= f.label :user_name %>
      <%= f.text_field :user_name %>
    </div>
    <div class="field">
      <%= f.label :funding_goal %>
      <%= f.text_field :funding_goal, label: "Amount", data: { role: 'money', a_sep: ',', a_dec: '.' } %>
    </div>
    <div class="field">
      <%= f.label :photo, "Photo of Child" %>
      <%= f.file_field :photo %>
    </div>
    <div class="field">
      <%= f.label :email_address %>
      <%= f.email_field :email_address, autofocus: true, placeholder:"Child's email address" %>
    </div>
    <br>
    <div class="actions">
      <%= f.submit "Add Child"%>
    </div>
  </div>
<% end %>

app/views/children/child_search.html.erb
<% if @children.length == 0%>
  <br>
  <div class="row">
    <div class="small-12 text-center">
      <h3>There are no children to show</h3>
    </div>
  </div>
<% end %>
<div id="child-search-result" class="row">
  <div class="small-10 small-pull-1 medium-push-1">
    <% @children.each do |child| %>
      <div  id="card" class="text-center small-8 small-push-2 medium-4 medium-pull-0 end column">
        <div id="image-container">
          <%= link_to image_tag(child.photo.url(:thumb), class: 'circle-image'), child_path(child) %>
        </div>
        <div id="progress-container">
          <div class="progress small-10 small-push-1" role="progressbar" tabindex="0" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
              <div class="progress-meter" style="width:<%= donationPercentage(child.funding_goal_cents, child.donations_amount_cents) %>;"><i class="fa fa-graduation-cap" aria-hidden="true"></i></div>
          </div>
        </div>
        <div id="information-container">
          <h4 class="truncate"><%= child.first_name %> <%= child.last_name %></h4>
          <h6 class="truncate"><%= child.user_name %></h6>
          <h6><%= child.birthday %></h6>
          <h6 class="truncate"><%= child.email_address %></h6>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/children/create.js.erb
$('#child-form').html('<%= escape_javascript(render('children/form')) %>');

app/views/children/edit.html.erb
<br>
<div class="row">
	<div class="small-12 text-center">
		<h4>Edit Your Child </h4>
		<%= form_for(@child, builder: FoundationFormBuilder, method: :put) do |f| %>
			<div class="field">
			  <%= f.label :first_name %>
			  <%= f.text_field :first_name %>
			</div>
			<div class="field">
			  <%= f.label :last_name %>
			  <%= f.text_field :last_name %>
			</div>
			<div class="field">
			  <%= f.label :birthdate %>
			  <div class="small-10 small-push-1 medium-6 medium-push-3">
			    <%= f.date_select :birthday, {order: [:day, :month, :year], prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }, start_year: Date.today.year - 18, end_year: Date.today.year - 100}, {required: true} %>
			  </div>
			</div>
			<div class="field">
			  <%= f.label :user_name %>
			  <%= f.text_field :user_name %>
			</div>
			<div class="field">
			  <%= f.label :photo, "Photo of Child" %>
			  <%= f.file_field :photo %>
			</div>
			<div class="field">
			  <%= f.label :email_address %>
			  <%= f.email_field :email_address, autofocus: true, placeholder:"Child's email address" %>
			</div>
			<br>
			<div class="actions">
			  <%= f.submit "Save"%>
			</div>
		<% end %>
	</div>
</div>

app/views/children/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<div class="text-center">
  <h4>My Children</h4>
</div>
<div id="child-information" class="row">
  <% @children.each do |child| %>
    <div  class="card text-center small-8 small-push-2 medium-4 medium-pull-0 end column">
      <div class="circle-img">
        <%= link_to image_tag(child.photo.url(:thumb), class:'circle-img'), child_path(child) %>
      </div>
      <div>
          <h6><%=  child.first_name %> <%=  child.last_name %></h6>
          <h6><%=  child.user_name %></h6>
          <h6><%=  child.birthday %></h6>
          <h6><%=  child.email_address %></h6>
      </div>
    </div>
  <% end %>
</div>
<br>
<div class="text-center">
  <%= link_to "Add Child", after_register_path(:your_children), class: "button" %>
</div>

app/views/children/new.html.erb
<br>
<div class="text-center">
	<h4>New Child</h4>
</div>
<%= render 'form', child: @child %>
<div class="row">
	<div class="small-12 text-center">
		<%= link_to 'Back', children_path, class: "button" %>
	</div>
</div>

app/views/children/show.html.erb
<br>
<div id="student-page">
	<div class="row">
		<div id="user-info" class="small-12 medium-6 column">
			<div class="small-12">
				<%= image_tag @child.photo.url(:thumb), class: 'circle-img float-center' %>
		    </div>
		    <br>
		    <div class="text-center">
		    	<h6><%= @child.first_name %> <%= @child.last_name %></h6>
		    	<h6><%= @child.birthday %></h6>
		    	<h6><%= @child.email_address %></h6>
		    </div>
	    </div>
	    <div class="small-12 medium-6 column">
	    	<div id="goal-container" class="">
	    		<div class="text-center">
	    			<h5><b>Student Fund Goal</b></h5>
	    		</div>
	    		<br>
	    		<div class="small-10 small-push-1">
	    			<h6><b>Goal:</b> <%= humanized_money_with_symbol @child.funding_goal %></h6>
	    			<h6><b>Current Amount:</b> <%= humanized_money_with_symbol @amount %></h6>
	    		</div>
			    <div class="progress small-10 small-push-1" role="progressbar" tabindex="0" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
  					<div class="progress-meter" style="width: <%= donationPercentage(@child.funding_goal_cents, @amount_cents) %>;"><i class="fa fa-graduation-cap" aria-hidden="true"></i></div>
				</div>
			    <div class="text-center">
			    	<%= link_to "Donate", new_child_donation_path(@child), class: "button" %></a>
				<% if can? :update, @child and @child.parent == current_user %>
					<%= link_to "Update Information", edit_child_path(@child), class: "button" %>
				<% end %>
				<%= link_to "Views Donations", child_donations_path(@child), class: "button" %>
			    </div>
		    </div>
	    </div>
	</div>
    <br>
    <% if @child.parent.present? %>
	    <div id="user-card" class="row">
	    	<div class="small-12 columns">
	    		<div class="small-12 medium-10 medium-push-1 columns">
		    		<h4>Student's Parent</h4>
		    	</div>
		    	<div  class="card text-center small-push-2 end columns">
				    <div class="circle-img">
				    	<%= link_to public_profile_path(profile: @child.parent.id) do %>
			        	<%= image_tag("slide01.jpg",:class => "circle-img") %>
			        <% end %>
				    </div>
			        <div>
						<h6><%= @child.parent.first_name %></h6>
						<h6><%= @child.parent.email %></h6>
				    </div>
			    </div>
		    </div>
	    </div>
    <% end %>
    <br>
    <% if @student_donors.count == 0 %>
    	<div class="row">
    		<div class="small-12 text-center">
    			<h4>This student doesn't have donnors</h4>
    		</div>
    	</div>
    <% else %>
	    <div id="user-card" class="row">
		    <div class="small-12 columns">
		    	<div class="small-12 medium-10 medium-push-1 columns">
		    		<h4>Student's donnors</h4>
		    	</div>
		    	<% @student_donors.uniq.each do |donor| %>
			    	<div  class="card text-center small-push-2 end columns">
				      	<div class="circle-img">
				    	<%= link_to donor_profile_path(donor) do %>
				    		<%= image_tag donor.avatar.url(:thumb), class: "circle-img" %>
				    	<% end %>
				    </div>
			     	<div>
			        	<h6><%= donor.first_name %></h6>
			        	<h6 class="truncate"><%= donor.email %></h6>
			      	</div>
			    	</div>
			    <% end %>
		    </div>
	    </div>
	<% end %>
</div>
<br>