config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root to: "home#index"
	devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "users/registrations" }

	resources :after_register
  resources :locations
  resources :children do
    resources :donations
  end
  resources :contributors

  get 'donor/profile', to: 'profiles#donor_profile', as: 'donor_profile'
  get 'student/profile', to: 'profiles#student_profile', as: 'student_profile'
  get 'parent/profile', to: 'profiles#parent_profile', as: 'parent_profile'
  get 'public/profile', to: 'profiles#public_profile', as: 'public_profile'
  get 'child/search', to: 'children#child_search', as: 'child_search'
  get 'key_students', to: 'contributors#key_student', as: 'key_student'
	get 'user_page/show', to: 'user_page#show', as: 'user_page_show'
end

app/models/contributor.rb
class Contributor < ApplicationRecord
  belongs_to :user
  has_many :relationships
  has_many :children, through: :relationships
  validates :email_address, presence: true, uniqueness: true
  validates :first_name, :last_name, presence: true

  scope :key_donors, -> (user) { where(user: user) }
  
  def full_name
    [first_name, last_name].join(' ')
  end
end

app/controllers/contributors_controller.rb
class ContributorsController < ApplicationController
	before_action :set_contributor, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  
  def index
    @user = current_user
    @contributors = Contributor.key_donors(@user)
  end

  def key_student
    @user = current_user
    @donor = Contributor.find_by(email_address: @user.email)
    @relationships = Relationship.donor_relationships(@donor) if @user.has_role? :donor
  end

  def show
    
  end

  def new
    
  end

  def edit
  end

  def create
    @user = current_user
    @contributor = Contributor.new(contributor_params)
    @contributor.user_id = @user.id

    respond_to do |format|
      if @contributor.save
        DonorMailer.donor_created(@contributor).deliver_later
        format.html { redirect_to after_register_path(:contributor), notice: 'Contributor was successfully created.' }
        format.json { render :show, status: :created, contributor: @contributor }
      else
        format.html { render :new }
        format.json { render json: @contributor.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @is_donor_registered = User.exists?(email: @contributor.email_address)
    respond_to do |format|
      if @contributor.update(contributor_params) and @is_donor_registered == false
        format.html { redirect_to @contributor, notice: 'Contributor was successfully updated.' }
        format.json { render :show, status: :ok, contributor: @contributor }
      else
        flash[:notice] = 'Contributor has already been registred'
        format.html { render :edit }
        format.json { render json: @contributor.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contributor.destroy
    respond_to do |format|
      format.html { redirect_to contributors_url, notice: 'Contributor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_contributor
      @contributor = Contributor.find(params[:id])
    end

    def contributor_params
      params.require(:contributor).permit(:first_name, :last_name, :email_address, :user_id, :relationship)
    end
end

app/helpers/contributors_helper.rb
module ContributorsHelper
end

app/views/contributors/_form.html.erb
<%= form_for Contributor.new, builder: FoundationFormBuilder, remote: true do |f| %>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :relationship, "Your Relationship to Child" %>
    <%= f.select :relationship, options_for_select(Relationship.names) %>
  </div>
  <div class="field">
    <%= f.label :email_address %>
    <%= f.email_field :email_address, autofocus: true, placeholder:"Contributor's email address" %>
  </div>
  <div class="actions">
    <%= f.submit "Invite Contributor"%>
  </div>
<% end %>

app/views/contributors/create.js.erb
$('#contributor-form').html('<%= escape_javascript(render('contributors/form')) %>');

app/views/contributors/edit.html.erb
<div class="row">
	<div class="small-12 text-center">
		<h4>Edit Donor </h4>
		<%= form_for(@contributor, builder: FoundationFormBuilder, method: :put) do |f| %>
			<div class="field">
			  <%= f.label :first_name %>
			  <%= f.text_field :first_name %>
			</div>
			<div class="field">
			  <%= f.label :last_name %>
			  <%= f.text_field :last_name %>
			</div>
			<div class="field">
			  <%= f.label :email_address %>
			  <%= f.email_field :email_address, autofocus: true, placeholder:"Donor's email address" %>
			</div>
			<br>
			<div class="actions">
			  <%= f.submit "Save"%>
			</div>
		<% end %>
	</div>
</div>

app/views/contributors/index.html.erb
<div class="text-center">
  <h4>Contributors</h4>
</div>
<div id="contributor-information" class="row">
  <% @contributors.each do |contributor| %>
    <div class="card text-center small-8 small-push-2 medium-4 medium-push-0 end column">
      <div class="circle-img">
        <%= link_to image_tag("slide01.jpg", class:'circle-img'), contributor_path(contributor) %>
      </div>
      <div>
        <h6><%=  contributor.first_name %> <%=  contributor.last_name %></h6>
        <h6><%=  contributor.email_address %></h6>
      </div>
    </div>
  <% end %>
</div>
<br>
<div class="text-center">
  <%= link_to "Add Contributor", after_register_path(:contributor), class: "button" %>
</div>
<br>

app/views/contributors/key_student.html.erb
<br>
<div class="text-center">
  <h4>Students</h4>
</div>
<div id="child-information" class="row">
  <% @relationships.each do |relationship| %>
    <div  class="card text-center small-8 small-push-2 medium-4 medium-pull-0 end column">
      <div class="circle-img">
        <%= link_to image_tag(relationship.child.photo.url(:thumb), class:'circle-img'), child_path(relationship.child) %>
      </div>
      <div>
          <h6><%=  relationship.child.first_name %> <%=  relationship.child.last_name %></h6>
          <h6><%=  relationship.child.user_name %></h6>
          <h6><%=  relationship.child.birthday %></h6>
          <h6><%=  relationship.child.email_address %></h6>
      </div>
    </div>
  <% end %>
</div>
<br>

app/views/contributors/new.html.erb
<div class="text-center">
	<br>
	<h4>Invite Contributors</h4>
</div>
<div class="callout small small-12 medium-6 medium-push-3">
	<%= render 'form', contributor: @contributor %>
</div>
<div class="row">
	<div class="small-12 text-center">
		<%= link_to 'Back', contributors_path, class: "button" %>
	</div>
</div>

app/views/contributors/show.html.erb
<br>
<div class="small-3 medium-1 float-center">
	<%= image_tag @contributor.avatar.url(:thumb), class: "circle-img float-center" %>
</div>
<br>
<div class="text-center">
	<h6><%= @contributor.first_name %> <%= @contributor.last_name %></h6>
	<h6><%= @contributor.email_address %></h6>
	<% if can? :update, @contributor and @value == false%>
		<%= link_to "Update Information", edit_contributor_path(@contributor), class: "button" %>
	<% end %>
</div>