config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root to: "home#index"
	devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "users/registrations" }

	resources :after_register
  resources :locations
  resources :children do
    resources :donations
  end
  resources :contributors

  get 'donor/profile', to: 'profiles#donor_profile', as: 'donor_profile'
  get 'student/profile', to: 'profiles#student_profile', as: 'student_profile'
  get 'parent/profile', to: 'profiles#parent_profile', as: 'parent_profile'
  get 'public/profile', to: 'profiles#public_profile', as: 'public_profile'
  get 'child/search', to: 'children#child_search', as: 'child_search'
  get 'key_students', to: 'contributors#key_student', as: 'key_student'
	get 'user_page/show', to: 'user_page#show', as: 'user_page_show'
end

app/views/layouts/_donor_header.html.erb
<header>
  <div class="expanded row">
    <div class="small-8 small-push-2 medium-4 medium-push-0 column">
      <%= link_to root_path do %>
        <%= image_tag("CollegeFundme_logo.png") %>
      <% end %>
    </div>
    <div class="small-12 medium-2 column">
      <ul class="dropdown menu" data-dropdown-menu>
        <li>
          <a href="#">Donnor</a>
          <ul class="menu">
            <li><%= link_to "My Profile", donor_profile_path %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
    </div>
    <div id="search-container" class="small-12 medium-6 column"> 
      <%= form_tag child_search_path, method: :get do %>
        <div class="small-9 medium-10 column">
          <%= text_field_tag :query, params[:query], placeholder: "Search for a child..."%> 
        </div>
        <div class="small-2 end column">
          <%= submit_tag "Search", name: nil, class: "button" %>
        </div>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/_footer.html.erb
<footer class="expanded row">
  <section>
    <div id="contact-us" class="small-10 small-push-1 medium-6 medium-push-0 columns">
      <h5>Send us a message</h5>
      <form>
        <div class="row">
          <div class="medium-6 columns">
            <label>
              <input type="text" placeholder="Name">
            </label>
          </div>
          <div class="medium-6 columns">
            <label>
              <input type="text" placeholder="Email">
            </label>
          </div>
          <div class="medium-12 columns">
            <label>
              <textarea rows="2" placeholder="Message"></textarea>
            </label>
          </div>
          <div class="medium-12 columns">
            <button type="button" class="button">Send</button>
          </div>
        </div>
      </form>
    </div>
  </section>
  <section>
    <div id="reach-us" class="small-10 small-push-1 medium-6 medium-push-0 columns">
      <h5>Other ways to reach us</h5>
      <ul class="no-bullet">
        <li><i class="fa fa-envelope-square"></i><h6>E-mail:</h6><p><a href="">example@email.com</a></p></li>
        <li><i class="fa fa-twitter-square"></i><h6>Twitter:</h6><p><a href="">@example</a></p></li>
        <li><i class="fa fa-phone-square"></i><h6>Phone:</h6><p>123-456-7890</p></li>
        <li><i class="fa fa-facebook-square"></i><h6>Facebook:</h6><p><a href="">facebook.com/example</a></p></li>
        <li><i class="fa fa-home"></i><h6>Adress:</h6><p>fake street, somewhere close</p></li>
        <li><i class="fa fa-linkedin-square"></i><h6>LinkedIn:</h6><p><a href=""> linkedin.com</a></p></li>
      </ul>
    </div>
  </section>
  <section>
    <div class="row">
      <div id="short-footer" class="small-12 text-center columns">
        <br>
        <p>&copy; Untitled Corp. All rights reserved. Lorem ipsum dolor sit amet feugiat tempus aliquam.</p>
        <ul class="menu menu-text-center">
          <li><a href="#">Terms of Use</a></li>
          <li><a href="#">Privacy Policy</a></li>
          <li><a href="#">Legal Information</a></li>
        </ul>
      </div>
    </div>
  </section>
</footer>
  

app/views/layouts/_header_logged_out.html.erb
<header id="header-logged-out">
  <div class="expanded row">
    <div class="small-8 small-push-2 medium-6 medium-push-0 columns">
      <%= link_to root_path do %>
        <%= image_tag("CollegeFundme_logo.png") %>
      <% end %>
    </div>
    <div class="small-5 small-push-1 medium-2 medium-push-2 large-1 large-push-3 columns"> 
      <%= link_to "Sign Up", new_user_registration_path, class:"button" %>
    </div>
    <div class="small-5 medium-2 large-1 columns">
      <%= link_to "Log In", new_user_session_path, class:"button" %>
    </div>
  </div>
</header>

app/views/layouts/_parent_header.html.erb
<header>
  <div class="expanded row">
    <div class="small-8 small-push-2 medium-4 medium-push-0 column">
      <%= link_to root_path do %>
        <%= image_tag("CollegeFundme_logo.png") %>
      <% end %>
    </div>
    <div class="small-12 medium-2 column">
      <ul class="dropdown menu" data-dropdown-menu>
        <li>
          <a href="#">Parent</a>
          <ul class="menu">
            <li><%= link_to "My Profile", parent_profile_path %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
    </div>
    <div id="search-container" class="small-12 medium-6 column"> 
      <%= form_tag child_search_path, method: :get do %>
        <div class="small-9 medium-10 column">
          <%= text_field_tag :query, params[:query], placeholder: "Search for a child..."%> 
        </div>
        <div class="small-2 end column">
          <%= submit_tag "Search", name: nil, class: "button" %>
        </div>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/_short_footer.html.erb
<footer class="expanded row">
  <div id="short-footer" class="small-12 text-center columns">
  	<br>
    <p>&copy; Untitled Corp. All rights reserved. Lorem ipsum dolor sit amet feugiat tempus aliquam.</p>
    <ul class="menu menu-text-center">
      <li><a href="#">Terms of Use</a></li>
      <li><a href="#">Privacy Policy</a></li>
      <li><a href="#">Legal Information</a></li>
    </ul>
  </div>
</footer>

app/views/layouts/_student_header.html.erb
<header>
  <div class="expanded row">
    <div class="small-8 small-push-2 medium-4 medium-push-0 column">
      <%= link_to root_path do %>
        <%= image_tag("CollegeFundme_logo.png") %>
      <% end %>
    </div>
    <div class="small-12 medium-2 column">
      <ul class="dropdown menu" data-dropdown-menu>
        <li>
          <a href="#">Student</a>
          <ul class="menu">
            <li><%= link_to "My Profile", student_profile_path %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
    </div>
    <div id="search-container" class="small-12 medium-6 column"> 
      <%= form_tag child_search_path, method: :get do %>
        <div class="small-9 medium-10 column">
          <%= text_field_tag :query, params[:query], placeholder: "Search for a child..."%> 
        </div>
        <div class="small-2 end column">
          <%= submit_tag "Search", name: nil, class: "button" %>
        </div>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CollegeFundMe</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= favicon_link_tag 'CollegeFund.me_icon.png' %>
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDiMwkJq_nPEBsa3a-WAL2TWnyS2mt7oUQ&libraries=places&sensor=false"></script>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if current_user.present? %>
      <% if current_user.has_role? :donor %>
        <%= render partial: 'layouts/donor_header' %>
      <% elsif current_user.has_role? :student %>
        <%= render partial: 'layouts/student_header' %>
      <% elsif current_user.has_role? :parent %>
        <%= render partial: 'layouts/parent_header' %>
      <% else %>
        <%= render partial: 'layouts/header_logged_out' %>
      <% end %>
    <% else %>
      <%= render partial: 'layouts/header_logged_out' %>
    <% end %>
    <%= yield %>
    <% if current_user.present? %>
      <%= render partial: 'layouts/short_footer' %>
    <% else %>
     <%= render partial: 'layouts/footer' %>
    <% end %>
  </body>
</html>